name: Publish Maven Artifact

on:
  push:
    branches:
      - master
    tags:
      - 'v.*'

permissions:
  contents: read

jobs:
  publish:
    uses: prayascodes/github-workflows/.github/workflows/gpr-publish.yml@main

    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}